name: 'Go Script'
description: 'Run a Go program'

inputs:
  go-version:
    description: 'The Go version to use'
    required: false
    default: 'stable'
  source:
    description: 'The Go source code'
    required: true
  layout:
    description: 'The Go layout'
    required: false
    default: |
      package main

      func main() {
        GO_SOURCE
      }

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - shell: bash
      run: |
        set -ex
        echo ${{ toJSON(inputs.layout) }} > layout.go
        echo ${{ toJSON(inputs.source) }} > source.go

        cat layout.go
        cat source.go

        SOURCE=$(<source.go)
        sed -i "s|GO_SOURCE|$SOURCE|" layout.go
        cat layout.go
        exit 0

        CODE=$(echo "$ESCAPED_LAYOUT" | sed "s/{ source }/$ESCAPED_SOURCE/")
        echo "$CODE" > main.go
        cat main.go
        goimports -w main.go
        cat main.go
        go run main.go
