name: 'Go Script'
description: 'Run a Go program'

inputs:
  go-version:
    description: 'The Go version to use'
    required: false
    default: 'stable'
  source:
    description: 'The Go source code'
    required: true
  layout:
    description: 'The Go layout'
    required: false
    default: |
      package main

      func main() {
        GO_SOURCE
      }

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - shell: bash
      run: |
        set -ex
        cat << 'EOF' > source.go
        ${{ inputs.source }}
        EOF
        cat << 'EOF' > layout.go
        ${{ inputs.layout }}
        EOF

        cat layout.go
        cat source.go

        SOURCE=$(cat source.go)
        awk -v replacement="$SOURCE" '
        {
          gsub(/GO_SOURCE/, replacement)
          print
        }' "layout.go" > "main.go"
        cat main.go

        goimports -w main.go
        cat main.go
        go run main.go
