name: 'Go Script'
description: 'Run a Go program'

inputs:
  dependencies:
    description: 'The Go dependencies, space separated'
    required: false
    default: ''
  go-version:
    description: 'The Go version to use'
    required: false
    default: 'stable'
  source:
    description: 'The Go source code'
    required: true
  template:
    description: 'The Go layout'
    required: false
    default: |
      package main

      func main() {
        GO_SOURCE
      }

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - shell: bash
      run: |
        go install golang.org/x/tools/cmd/goimports@latest

    - name: 'Create Project'
      shell: bash
      run: |
        GO_PROJECT=$(mktemp -d)
        echo "GO_PROJECT=$GO_PROJECT" >> $GITHUB_ENV
        cd "$GO_PROJECT"
        go mod init m

    - name: 'Install Dependencies'
      shell: bash
      working-directory: ${{ env.GO_PROJECT }}
      run: |
        set -ex
        for dep in ${{ inputs.dependencies }}; do
          go get -u $dep
        done

    - name: 'Add GHA package'
      shell: bash
      working-directory: ${{ env.GO_PROJECT }}
      run: |
        mkdir -p gha
        cat << 'EOF' > gha/gha.go
        package gha

        import "os"

        func WriteStepSummary(content string) error {
          path := os.Getenv("GITHUB_STEP_SUMMARY")
          file, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0644)
          if err != nil {
              return err
          }
          defer file.Close()

          _, err = file.WriteString(content)
          return err
        }
        EOF

    - name: 'Generate Script'
      shell: bash
      working-directory: ${{ env.GO_PROJECT }}
      run: |
        set -ex
        cat << 'EOF' > source.go
        ${{ inputs.source }}
        EOF
        cat << 'EOF' > template.go
        ${{ inputs.template }}
        EOF

        SOURCE=$(cat source.go)
        awk -v replacement="$SOURCE" '
        {
          gsub(/GO_SOURCE/, replacement)
          print
        }' "template.go" > "main.go"

        goimports -w main.go
        go mod tidy

    - name: 'Run Script'
      shell: bash
      working-directory: ${{ env.GO_PROJECT }}
      run: |
        cat main.go
        ls
        ls gha
        cat gha/gha.go
        go run main.go

