name: 'Go Script'
description: 'Run a Go program'

inputs:
  go-version:
    description: 'The Go version to use'
    required: false
    default: 'stable'
  source:
    description: 'The Go source code'
    required: true
  layout:
    description: 'The Go layout'
    required: false
    default: |
      package main

      func main() {
        { source }
      }

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - shell: bash
      run: |
        set -ex
        # Escape quotes in the inputs
        LAYOUT="${{ inputs.layout }}"
        SOURCE="${{ inputs.source }}"
        ESCAPED_LAYOUT=$(echo "$LAYOUT" | sed 's/"/\\"/g')
        ESCAPED_SOURCE=$(echo "$SOURCE" | sed 's/"/\\"/g')

        # Write the escaped inputs to files
        echo "$ESCAPED_LAYOUT" > layout.go
        echo "$ESCAPED_SOURCE" > source.go

        # Output the contents for verification
        cat layout.go
        cat source.go
        exit 0

        CODE=$(echo "$ESCAPED_LAYOUT" | sed "s/{ source }/$ESCAPED_SOURCE/")
        echo "$CODE" > main.go
        cat main.go
        goimports -w main.go
        cat main.go
        go run main.go
