name: 'Go Script'
description: 'Run a Go program'

inputs:
  go-version:
    description: 'The Go version to use'
    required: false
    default: 'stable'
  source:
    description: 'The Go source code'
    required: true
  template:
    description: 'The Go layout'
    required: false
    default: |
      package main

      func main() {
        GO_SOURCE
      }

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - shell: bash
      run: |
        go install golang.org/x/tools/cmd/goimports@latest

    - shell: bash
      run: |
        GO_PROJECT=$(mktemp -d)
        echo "GO_PROJECT=$GO_PROJECT" >> $GITHUB_ENV
        cd "$GO_PROJECT"
        go mod init m

    - shell: bash
      working-directory: ${{ env.GO_PROJECT }}
      run: |
        set -ex
        pwd
        cat << 'EOF' > source.go
        ${{ inputs.source }}
        EOF
        cat << 'EOF' > template.go
        ${{ inputs.template }}
        EOF

        SOURCE=$(cat source.go)
        awk -v replacement="$SOURCE" '
        {
          gsub(/GO_SOURCE/, replacement)
          print
        }' "template.go" > "main.go"

        goimports -w main.go
        go run main.go
