name: 'Test'

on:
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: klahr/go-inline@master
        with:
          source: |
            fmt.Println("Hello, World!")

