name: 'Test'

on:
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  Test:
    outputs:
      MY_OUTPUT: ${{ steps.run.outputs.MY_OUTPUT }}
    runs-on: ubuntu-latest
    steps:
      - uses: klahr/go-inline@master
        id: run
        with:
          dependencies: "github.com/google/uuid github.com/pkg/errors@v0.9.1"

          source: |
            fmt.Println("Hello, World!")
            id := uuid.New()
            fmt.Println(id.String())
            fmt.Println(errors.New("Hello, world!"))
            gha.WriteStepSummary("# Yay")
            gha.WriteStepSummary("## Good stuff")
            gha.SetEnv("GITHUB_ENV", "MY_ENV", "myenv")
            gha.SetEnv("GITHUB_OUTPUT", "MY_OUTPUT", "myoutput")

      - run: |
         echo "$FOO"

  Output:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - run: |
          echo "${{ needs.Test.outputs.MY_OUTPUT }}"

