name: 'Test'

on:
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  Test:
    outputs:
      FOO_OUT: ${{ steps.run.outputs.FOO_OUT }}
    runs-on: ubuntu-latest
    steps:
      - uses: klahr/go-inline@master
        id: run
        with:
          dependencies: "github.com/google/uuid github.com/pkg/errors@v0.9.1"

          source: |
            fmt.Println("Hello, World!")
            id := uuid.New()
            fmt.Println(id.String())
            fmt.Println(errors.New("Hello, world!"))
            gha.WriteStepSummary("# Yay")
            gha.WriteStepSummary("## Good stuff")
            gha.SetEnv("GITHUB_ENV", "FOO", "bar")
            gha.SetEnv("GITHUB_OUTPUT", "FOO_OUT", "bar_out")

      - run: |
         echo "$FOO"
         echo "${{ steps.run.outputs.FOO_OUT }}"

  Output:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - run: |
          echo "$FOO"
          echo "${{ needs.Test.outputs.FOO_OUT }}"
