name: 'Test'

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: klahr/go-inline@master
        id: run
        with:
          dependencies: "github.com/google/uuid github.com/pkg/errors@v0.9.1"

          source: |
            fmt.Println("Hello, World!")
            id := uuid.New()
            fmt.Println(id.String())
            fmt.Println(errors.New("Hello, world!"))
            gha.WriteStepSummary("# Yay")
            gha.WriteStepSummary("## Good stuff")
            gha.SetKeyValue("GITHUB_ENV", "MY_ENV", "myenv")
            if output, err := gha.Exec("lsasdf", []string{"-a", "-l", "-h"}); err != nil {
              fmt.Println(err)
            } else {
              fmt.Println(output)
            }
      - run: |
         echo "$MY_ENV"

