name: 'Test'

on:
  workflow_dispatch:


jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: klahr/go-version@master
        with:
          source: |
            fmt.Println("Hello, World!")

